"""added_1_N_tags_tasks

Revision ID: cac5cf55cffa
Revises: bcd9334a523e
Create Date: 2024-11-22 00:43:39.524996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac5cf55cffa'
down_revision = 'bcd9334a523e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_tag_id_tags'), 'tags', ['tag_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_tag_id_tags'), type_='foreignkey')
        batch_op.drop_column('tag_id')

    # ### end Alembic commands ###
