"""added_unique_requirement

Revision ID: abda7a6fc6af
Revises: f9749b66f5da
Create Date: 2024-11-19 17:45:13.241461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abda7a6fc6af'
down_revision = 'f9749b66f5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tags_name')
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.create_index('ix_tags_name', ['name'], unique=False)

    # ### end Alembic commands ###
